### ISSUE TITLE
NPE in NdlGenerator

### ISSUE THREAD

**Issue by hinchliff** [RENCI-NRIG/orca5#100]
I'm trying to test Orca, using Ahab.  I'm sure I'm doing something incorrect, but Orca probably shouldn't be throwing a NullPointerException here:

> Exception in thread "main" java.lang.NullPointerException
	at orca.ndl.NdlGenerator.addProperty([NdlGenerator.java:340](https://github.com/RENCI-NRIG/orca5/blob/orca-5.0.2/ndl/src/main/java/orca/ndl/NdlGenerator.java#L340))
	at orca.ndl.NdlGenerator.addInterfaceToIndividual(NdlGenerator.java:732)
	at org.renci.ahab.libndl.ndl.NewSliceModel.add(NewSliceModel.java:184)
	at org.renci.ahab.libndl.SliceGraph.addStitch(SliceGraph.java:237)
	at org.renci.ahab.libndl.resources.request.ComputeNode.stitch(ComputeNode.java:223)

There are some `assert` statements at the beginning of [addProperty()](https://github.com/RENCI-NRIG/orca5/blob/orca-5.0.2/ndl/src/main/java/orca/ndl/NdlGenerator.java#L332), checking for `null` inputs, but, by default, [assertions are disabled at runtime](https://docs.oracle.com/javase/8/docs/technotes/guides/language/assert.html#enable-disable).

And the public method calling addProperty(), [addInterfaceToIndividual()](https://github.com/RENCI-NRIG/orca5/blob/orca-5.0.2/ndl/src/main/java/orca/ndl/NdlGenerator.java#L731) doesn't verify the inputs.

Turning assertions on when running my Ahab application, results in the following AssertionError:
> Exception in thread "main" java.lang.AssertionError
	at orca.ndl.NdlGenerator.addProperty([NdlGenerator.java:332](https://github.com/RENCI-NRIG/orca5/blob/orca-5.0.2/ndl/src/main/java/orca/ndl/NdlGenerator.java#L332))
	at orca.ndl.NdlGenerator.addInterfaceToIndividual(NdlGenerator.java:732)
	at org.renci.ahab.libndl.ndl.NewSliceModel.add(NewSliceModel.java:184)
	at org.renci.ahab.libndl.SliceGraph.addStitch(SliceGraph.java:237)
	at org.renci.ahab.libndl.resources.request.ComputeNode.stitch(ComputeNode.java:223)

I'm not sure if this means there is a bug in Ahab or not.  But it's probably not correct behavior for Orca to throw NPE.

**Comment by ibaldin** [comment]
Based on the discussion - there likely are two things that need to be fixed - one - NdlGenerator should be hardened to check input parameters, and two Ahab needs to be hardened not to allow this to happen.
