### ISSUE TITLE
Broadcast domain and Stitchport result in NPE

### ISSUE THREAD

**Issue by hinchliff** [RENCI-NRIG/orca5#126]
From @mcevik0 
>I’m receiving exceptions when I create a slice with a VM connected to a stitchport via a broadcast link.
> ```VM===BroadcastLink===Stitchport```

The exception is a NullPointerException:
```
java.lang.NullPointerException
	at orca.embed.cloudembed.controller.InterDomainHandler.runEmbedding(InterDomainHandler.java:108))
	at orca.embed.cloudembed.controller.MultiPointHandler.runEmbedding(MultiPointHandler.java:127)
	at orca.embed.cloudembed.controller.InterCloudHandler.runEmbedding(InterCloudHandler.java:124)
	at orca.embed.workflow.RequestWorkflow.run(RequestWorkflow.java:162)
```
That's a logging statement at [InterDomainHandler.java:108](https://github.com/RENCI-NRIG/orca5/blob/orca-5.1.4/embed/src/main/java/orca/embed/cloudembed/controller/InterDomainHandler.java#L108).

Unfortunately just moving the `logger` line to after the null checks doesn't fix the problem, as testing that results in the slice being empty:
```
2017-04-27 09:19:31,982 [main] DEBUG controller.OrcaXmlrpcHandler-(OrcaXmlrpcHandler.java:415) - createSlice(): returning result Here are the leases: 
Request id: 06ce5804-48a6-4c34-9c5f-dcb3469a0094
No new reservations were computed
```

There doesn't seem to be an obvious easy fix here.  

I am tempted to delay fixing this one for a while, while I work on some other things. But if this is needed for SciDAS, I can put it at a higher priority.    

Is there any way to get similar functionality by working with a slightly different topology?  Or is this a bug we need to fix now?

**Comment by hinchliff** [comment]
Fixed in #127
