### ISSUE TITLE
Upgrade Jena to 3.3.x

### ISSUE THREAD

**Issue by ibaldin** [RENCI-NRIG/orca5#136]
We are using 1.0.2 from 2014 when 3.3.x is available. Should attempt to upgrade, minding the fact that Gleen may present a dependency @vjorlikowski

**Comment by ibaldin** [comment]
May help solve #121

**Comment by vjorlikowski** [comment]
I have a version of GLEEN that has been ported to JENA 3.3.0 (and is also using commons-logging 1.2) ready to test.
We will need to change all imports using "com.hp.hpl" to "org.apache" for JENA imports, for this to work.

**Comment by mjstealey** [comment]
Observed JENA error (`com.hp.hpl.jena.tdb.base.file.FileException`) when running `mvn clean install -Ptest` from a CentOS 7 emulation environment (VirutalBox VM). Multiple instances of same error. Example below:

```
Starting Orca Regression Test TS1-1.rdf
2017-09-12 09:55:56,889 [main] DEBUG controller.MockXmlRpcController-(MockXmlRpcController.java:77) - initializing MockOrcaConnectionFactory
2017-09-12 09:55:56,889 [main] INFO  controller-(MockXmlRpcController.java:137) - Initializing the XMLRPC controller
2017-09-12 09:55:56,900 [main] DEBUG controller.MockXmlRpcController-(MockXmlRpcController.java:77) - initializing MockOrcaConnectionFactory
2017-09-12 09:55:56,908 [main] INFO  controller-(MockXmlRpcController.java:144) - Starting support threads
2017-09-12 09:55:56,938 [main] INFO  controller.OrcaXmlrpcHandler-(OrcaXmlrpcHandler.java:261) - ORCA API createSlice() invoked
2017-09-12 09:55:58,026 [main] ERROR controller.OrcaXmlrpcHandler-(OrcaXmlrpcHandler.java:2482) - checkMemory(): unable to test for presence of disable file null
2017-09-12 09:55:58,028 [main] ERROR controller.OrcaXmlrpcHandler-(OrcaXmlrpcHandler.java:2490) - checkMemory(): Unable to parse memory threshold value, proceeding
2017-09-12 09:55:58,028 [main] ERROR controller.OrcaXmlrpcHandler-(OrcaXmlrpcHandler.java:285) - Setting userDN to test. This should only happen in Unit Testing.
2017-09-12 09:55:58,870 [main] DEBUG controller.XmlrpcOrcaState-(XmlrpcOrcaState.java:282) - getSlice(): this slice ID=null for urn=createSlice_testRegressionTest_TS1-1.rdf
2017-09-12 09:55:58,903 [main] ERROR controller.OrcaXmlrpcHandler-(OrcaXmlrpcHandler.java:424) - createSlice(): Exception encountered: Unable to create TDB IDM database due to NDL error: orca.ndl.NdlException: Unable to create blank model due to: com.hp.hpl.jena.tdb.base.file.FileException: BlockMgrMapped.segmentAllocate: Segment = 0
java.lang.RuntimeException: Unable to create TDB IDM database due to NDL error: orca.ndl.NdlException: Unable to create blank model due to: com.hp.hpl.jena.tdb.base.file.FileException: BlockMgrMapped.segmentAllocate: Segment = 0
	at orca.controllers.xmlrpc.XmlrpcControllerSlice.<init>(XmlrpcControllerSlice.java:109)
	at orca.controllers.xmlrpc.OrcaXmlrpcHandler.createSlice(OrcaXmlrpcHandler.java:309)
	at orca.controllers.xmlrpc.OrcaXmlrpcHandlerTest.doTestCreateSlice(OrcaXmlrpcHandlerTest.java:112)
	at orca.controllers.xmlrpc.OrcaRegressionTest.testOrcaRegressionTests(OrcaRegressionTest.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:134)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
```

Adding to issue per suggestion of @hinchliff

**Comment by ibaldin** [comment]
It's trying to create a file to store the IDM (Inter Domain Model) in TDB format (Jena's internal persistent RDF store) and failing. Not clear why from the error. 

Seems there is a discussion of this here https://github.com/stain/jena-docker/issues/1

**Comment by ibaldin** [comment]
The gleen issue has been resolved and tested in RENCI-NRIG/orca5#95 - we have a version of Gleen that works with Jena 3.3.0
