### ISSUE TITLE
Modify adding Inter-Domain Broadcast links results in NullPointerException

### ISSUE THREAD

**Issue by hinchliff** [RENCI-NRIG/orca5#162]
Reported by @paul-ruth 

1. Start a new slice with three nodes, in different domains, with _no_ links between them. Create this slice.
1. Modify the slice by adding a _broadcast_ link between two nodes (A and B). Submit this modify.
1. Modify the slice by adding a _broadcast_ link between two nodes (B and C). Submit this modify.
1. `Exception encountered while submitting slice modify request to ORCA: Unable to modify slice: ERROR: ModifySlice Exception!java.lang.NullPointerException`

![modifyaddinterdomainbroadcastlink](https://user-images.githubusercontent.com/10090677/33784253-1761116e-dc2e-11e7-93df-88cceea21588.png)

**Comment by paul-ruth** [comment]
Also, this is blocking Yuanjun's progress on the next step for the CICI SAFE work.

**Comment by hinchliff** [comment]
This is the details on the NPE:

```
java.lang.NullPointerException
	at orca.embed.cloudembed.controller.InterDomainHandler.createManifest(InterDomainHandler.java:942)
	at orca.embed.cloudembed.controller.ModifyHandler.createManifest(ModifyHandler.java:807)
	at orca.embed.cloudembed.controller.ModifyHandler.modifySlice(ModifyHandler.java:159)
	at orca.embed.workflow.RequestWorkflow.modify(RequestWorkflow.java:249)
	at orca.controllers.xmlrpc.OrcaXmlrpcHandler.modifySlice(OrcaXmlrpcHandler.java:597)
```

The VLAN from the first modify (VLAN1 in this case) is what was causing the NPE.  Looks like, since that part of the model is `closed`, it should not be added to the manifest?

I have a test and fix ready to go for this.
