### ISSUE TITLE
Exception in nlr control after the handler failed.

### ISSUE THREAD

**Issue by YufengXin** [RENCI-NRIG/orca5#67]
A recent outrage of the DD switch at Departure Dr. failed redeeming the reservation at the nlr actor, which subsequently caused a Exception in the NLR control code. This needs to be evaluated, note it seems to be a new bug introduced by the latest change the network control code to accommodate the stitchingport on  BEN.

https://github.com/RENCI-NRIG/exogeni/issues/63

-----------------------------------------------------
INFO   | jvm 1    | 2016/08/25 21:03:30 |      [echo] Provisioning DD action 1
INFO   | jvm 1    | 2016/08/25 21:03:30 |      [echo] DD join action 1 on router 192.168.209.3: vlan=100 bw=10000000/1250000 ports=xe-0/0/1,xe-0/0/0
INFO   | jvm 1    | 2016/08/25 21:03:30 |      [echo] enabling vlan 100 on router 192.168.209.3 bw=10000000 burst=1250000
INFO   | jvm 1    | 2016/08/25 21:03:30 |      [echo] router.user: geni-orca
INFO   | jvm 1    | 2016/08/25 21:04:33 |      [echo] DDLeave actions 1
INFO   | jvm 1    | 2016/08/25 21:04:33 |      [echo] DeProvisioning DD action 1
INFO   | jvm 1    | 2016/08/25 21:04:33 |      [echo] DD leave action 1 on router 192.168.209.3: vlan=100 ports=xe-0/0/1,xe-0/0/0
INFO   | jvm 1    | 2016/08/25 21:04:33 |      [echo] removing ports xe-0/0/1,xe-0/0/0 from vlan 100 on router 192.168.209.3
INFO   | jvm 1    | 2016/08/25 21:04:33 |      [echo] vlan 100 removed ports xe-0/0/1,xe-0/0/0 on router 192.168.209.3
INFO   | jvm 1    | 2016/08/25 21:04:33 |      [echo] disabling vlan 100 (qos status true) on router 192.168.209.3
INFO   | jvm 1    | 2016/08/25 21:05:36 |      [echo] Stopping atomic sequence for DEPARTURE DRIVE
INFO   | jvm 1    | 2016/08/25 21:05:36 | 
INFO   | jvm 1    | 2016/08/25 21:05:36 | BUILD FAILED
INFO   | jvm 1    | 2016/08/25 21:05:36 | /etc/orca/am+broker-12080/handlers/providers/departuredrive/handler.xml:71: The following error occurred while executing this line:
INFO   | jvm 1    | 2016/08/25 21:05:36 | /etc/orca/am+broker-12080/handlers/providers/departuredrive/handler.xml:51: The following error occurred while executing this line:
INFO   | jvm 1    | 2016/08/25 21:05:36 | /etc/orca/am+broker-12080/handlers/providers/departuredrive/dd.tasks.xml:223: The following error occurred while executing this line:
INFO   | jvm 1    | 2016/08/25 21:05:36 | /etc/orca/am+broker-12080/handlers/providers/departuredrive/dd.tasks.xml:241: The following error occurred while executing this line:
INFO   | jvm 1    | 2016/08/25 21:05:36 | /etc/orca/am+broker-12080/handlers/providers/departuredrive/dd.tasks.xml:55: The following error occurred while executing this line:
INFO   | jvm 1    | 2016/08/25 21:05:36 | /etc/orca/am+broker-12080/handlers/providers/departuredrive/dd.tasks.xml:252: The following error occurred while executing this line:
INFO   | jvm 1    | 2016/08/25 21:05:36 | /etc/orca/am+broker-12080/handlers/providers/departuredrive/dd.tasks.xml:266: The following error occurred while executing this line:
INFO   | jvm 1    | 2016/08/25 21:05:36 | /etc/orca/am+broker-12080/handlers/providers/departuredrive/dd.tasks.xml:162: The following error occurred while executing this line:
INFO   | jvm 1    | 2016/08/25 21:05:36 | /etc/orca/am+broker-12080/handlers/providers/ben.no-na.tasks.xml:236: /etc/orca/am+broker-12080/handlers/providers/ben.no-na.tasks.xml:299: An error occurred: Unable to connect to device
INFO   | jvm 1    | 2016/08/25 21:05:36 | 
INFO   | jvm 1    | 2016/08/25 21:05:36 | Total time: 2 minutes 6 seconds
INFO   | jvm 1    | 2016/08/25 21:05:36 | null:null:null
INFO   | jvm 1    | 2016/08/25 21:05:36 | java.lang.NullPointerException: Name is null
INFO   | jvm 1    | 2016/08/25 21:05:36 |   at java.lang.Enum.valueOf(Enum.java:235)
INFO   | jvm 1    | 2016/08/25 21:05:36 |   at orca.ndl.LayerConstant$Layer.valueOf(LayerConstant.java:18)
INFO   | jvm 1    | 2016/08/25 21:05:36 |   at orca.embed.cloudembed.ConnectionManager.returnLabel(ConnectionManager.java:889)
INFO   | jvm 1    | 2016/08/25 21:05:36 |   at orca.embed.cloudembed.ConnectionManager.switchingActionInModel(ConnectionManager.java:457)
INFO   | jvm 1    | 2016/08/25 21:05:36 |   at orca.embed.cloudembed.ConnectionManager.releaseCRS(ConnectionManager.java:416)
INFO   | jvm 1    | 2016/08/25 21:05:36 |   at orca.embed.cloudembed.ConnectionManager.releaseInModel(ConnectionManager.java:697)
INFO   | jvm 1    | 2016/08/25 21:05:36 |   at orca.embed.cloudembed.NetworkHandler.releaseReservation(NetworkHandler.java:338)
INFO   | jvm 1    | 2016/08/25 21:05:36 |   at orca.plugins.ben.control.BenNdlControl.closeConnectionCleanup(BenNdlControl.java:318)
INFO   | jvm 1    | 2016/08/25 21:05:36 |   at orca.plugins.ben.control.BenNdlControl.configurationComplete(BenNdlControl.java:345)
INFO   | jvm 1    | 2016/08/25 21:05:36 |   at orca.policy.core.AuthorityCalendarPolicy.configurationComplete(AuthorityCalendarPolicy.java:528)
INFO   | jvm 1    | 2016/08/25 21:05:36 |   at orca.shirako.plugins.ShirakoPlugin.processConfigurationComplete(ShirakoPlugin.java:249)
INFO   | jvm 1    | 2016/08/25 21:05:36 |   at orca.shirako.plugins.ShirakoPlugin$ConfigurationCompleteEvent.process(ShirakoPlugin.java:378)
INFO   | jvm 1    | 2016/08/25 21:05:36 |   at orca.shirako.core.Actor.actorMain(Actor.java:377)
INFO   | jvm 1    | 2016/08/25 21:05:36 |   at orca.shirako.core.Actor$4.run(Actor.java:1018)
INFO   | jvm 1    | 2016/08/25 21:05:36 |   at java.lang.Thread.run(Thread.java:745)

 @ibaldin @mcevik0

**Comment by YufengXin** [comment]
fixed in 11c8055b7e22070597c5d9cdfcec683c9ea8b4c5, which also fixed the NPE when deleting a slice with a stitching port on BEN reported yesterday.
